In [1]:
import socket
import pickle
import numpy as np
import os
import time

from game.run import Agent

In [2]:
agent = Agent()

In [3]:
for _ in range(20):
    agent.step_to(1)
    print(agent.get_env())

(array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]]), 2, 0, False)
pickle data was truncated
None
invalid load key, '\x00'.
None
(array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]]), 1, 0, False)
pickle data was truncated
None
invalid load key, '\x00'.
None
(array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]]), 1, 0, False)
(array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0.

ConnectionResetError: [Errno 54] Connection reset by peer

In [48]:
agent.step_to(1)

In [49]:
print(agent.get_env())

ConnectionResetError: [Errno 54] Connection reset by peer